import { connectDB } from "@/lib/db/mongoose"
import { Investment } from "@/lib/models/Investment"
import { Business } from "@/lib/models/Business"
import { getSessionUser } from "@/lib/middleware/auth"
import { NextResponse } from "next/server"

export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const user = await getSessionUser()
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 })

  const { id } = await params
  await connectDB()
  const investment = await Investment.findById(id)
  if (!investment) return NextResponse.json({ error: "Not found" }, { status: 404 })
  const business = await Business.findById(investment.businessId)

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Investment Agreement</title>
  <style>body{font-family:system-ui;padding:24px;line-height:1.6}h1{font-size:20px}</style></head><body>
  <h1>Investment Agreement</h1>
  <p><strong>Investor:</strong> ${user.name} (${user.email})</p>
  <p><strong>Business:</strong> ${business?.name || investment.businessId.toString()}</p>
  <p><strong>Amount:</strong> ${investment.amount}</p>
  <p><strong>Date:</strong> ${new Date(investment.createdAt).toLocaleString()}</p>
  <hr/>
  <p><strong>Terms & Conditions:</strong></p>
  <p>This agreement confirms the investment detailed above. This is a non-binding preview document generated by the platform. For legally binding agreements, consult appropriate legal counsel.</p>
  </body></html>`

  return new NextResponse(html, {
    status: 200,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  })
}

